from enum import Enum

CAMERA_TYPE = ["","1/2","1/1.8","2/3","1","1.1"]
REQUIRE_STYLE = '''background: yellow;'''
GRAY_STYLE = '''background: LIGHTGRAY;'''
RESULT_STYLE = '''background: LIGHTPINK;'''

DESIGN_DB_NAME = "design"
CAMERA_TABLE_NAME = "camera"
LENS_TABLE_NAME = "lens"

SPEC = "SPECIFICATION"
PIX_X = "Pix_H"
PIX_Y = "Pix_V"
CCD_X = "CCD_H"
CCD_Y = "CCD_V"
IMG_SIZE = "IMAGE_SIZE"
SUMMARY = "SUMMARY"
MAKER = "MAKER"
URL = "URL"
MAGNIFICATION = "MAGNIFICATION"
DEPTH ="DEPTH"
FOCAL_DISTANCE = "FOCAL_DISTANCE"
OI_DISTANNCE ="OI_DISTANNCE"
WD ="WD"
FOV_X = "FOV_X"
FOV_Y = "FOV_Y"

class Calc(Enum):
    FOV = 1
    WD = 2
    FOCAL_DISTANCE = 3
    MAGN_FROM_CCD = 4
    RESOLUTION = 5

DESIGN_DB_NAME = "design"
LENS_TABLE_NAME = "lens"
CAMERA_TYPE = ["","1/2","1/1.8","2/3","1","1.1"]
SPEC = "SPECIFICATION"
MAGNIFICATION = "MAGNIFICATION"
DEPTH ="DEPTH"
IMG_SIZE = "IMAGE_SIZE"
SUMMARY = "SUMMARY"
MAKER = "MAKER"
URL = "URL"

FOCAL_DISTANCE = "FOCAL_DISTANCE"
OI_DISTANNCE ="OI_DISTANNCE"
WD ="WD"
FOV_X = "FOV_X"
FOV_Y = "FOV_Y"